import Head from 'next/head';

import { Home } from '@/features/browse';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>RickAndMorty | Browse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </>
  );
}
